spring.application.name=medicorehospitalmanagement


spring.datasource.url=jdbc:mariadb://localhost:3306/hospitalmanagement
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring security
# spring.security.user.name=muskan
# spring.security.user.password=muskan23

jwt.secretKey=hth52rujqx65f6r7fd3fpm65d29ed8zed2fg2fvsytb5sdkqd1sf7aegfhyu5kuimsg5

# spring.security.oauth2.client.registration.google.client-id=p